/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lpr_FileSysUtil */

#ifndef _Included_com_lpr_FileSysUtil
#define _Included_com_lpr_FileSysUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lpr_FileSysUtil
 * Method:    sdcard_reset
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_lpr_FileSysUtil_sdcard_1reset
  (JNIEnv *, jobject);

/*
 * Class:     com_lpr_FileSysUtil
 * Method:    sdcard_getcapacity
 * Signature: ()Z
 */
JNIEXPORT jint JNICALL Java_com_lpr_FileSysUtil_sdcard_1getcapacity
        (JNIEnv *, jobject);

/*
 * Class:     com_lpr_FileSysUtil
 * Method:    sdcard_create
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_lpr_FileSysUtil_sdcard_1create
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_lpr_FileSysUtil
 * Method:    sdcard_write
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_lpr_FileSysUtil_sdcard_1write
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_lpr_FileSysUtil
 * Method:    sdcard_update
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_lpr_FileSysUtil_sdcard_1update
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_lpr_FileSysUtil
 * Method:    sdcard_open
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_lpr_FileSysUtil_sdcard_1open
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_lpr_FileSysUtil
 * Method:    sdcard_read
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_lpr_FileSysUtil_sdcard_1read
  (JNIEnv *, jobject, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
